#!/bin/python

from contextlib import contextmanager
import os
import os.path as p
import subprocess as sub

self_path = p.dirname(p.abspath(__file__))
root_path = p.dirname(self_path)

@contextmanager
def working_directory(path):
    old_path = os.getcwd()
    sub.check_call(["mkdir", "-p", path])
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(old_path)

def main():
    aro_exec = "aronnax_core"
    with working_directory(root_path):
        sub.check_call(["make", aro_exec])
    env = dict(os.environ, GFORTRAN_STDERR_UNIT="17")
    if 'ARONNAX_TEST_VALGRIND_ALL' in os.environ:
        sub.check_call(["valgrind", "--error-exitcode=5", p.join(root_path, aro_exec)],
            env=env)
    else:
        sub.check_call([p.join(root_path, aro_exec)], env=env)

if __name__ == '__main__':
    main()
